# Limpeza dos dados

## Importando as Bilbiotecas

In [10]:
import pandas as pd

## Extraindo os dados

In [11]:
dataframe = pd.read_csv('data/ocorrencia_2010_2020.csv',  sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True)
dataframe.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

Localizando indices e labels do dataframe

In [12]:
dataframe.loc[1,'ocorrencia_cidade']

'BELÉM'

In [13]:
dataframe.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO

In [14]:
dataframe.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,39789,39789,39789,39789,39789,INCIDENTE,NaN,NaN,SÃO PEDRO DO SUL,RS,...,2010-01-10,21:30:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
40,39158,39158,39158,39158,39158,INCIDENTE,***,***,BELÉM,PA,...,2010-01-28,16:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [15]:
dataframe.loc[:,'ocorrencia_cidade']

0           RIO DE JANEIRO
1                    BELÉM
2           RIO DE JANEIRO
3       LUCAS DO RIO VERDE
4                  PELOTAS
               ...
5747              CAMPINAS
5748     LAGOA DA CONFUSÃO
5749        RIO DE JANEIRO
5750             VICENTINA
5751        RIO DE JANEIRO
Name: ocorrencia_cidade, Length: 5752, dtype: object

## ALterando o indice do dataframe

Verificando os atributos que possuem valores unicos

In [16]:
dataframe.codigo_ocorrencia.is_unique

True

O atributo codigo_ocorrencia pode ser utilizado como indice por possuirem valores unicos

In [17]:
dataframe.set_index('codigo_ocorrencia', inplace=True)
dataframe

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
39527,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79804,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,2020-12-29,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79757,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,2020-12-30,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79802,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,2020-12-30,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79756,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,2020-12-31,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
79844,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,2020-12-31,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [18]:
dataframe.loc[40324]

codigo_ocorrencia1                              40324
codigo_ocorrencia2                              40324
codigo_ocorrencia3                              40324
codigo_ocorrencia4                              40324
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                             PELOTAS
ocorrencia_uf                                      RS
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBPK
ocorrencia_dia                    2010-01-05 00:00:00
ocorrencia_hora                              19:25:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       NaN
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 40324, dtype: object

Resetando o indice criado do dataframe

In [19]:
dataframe.reset_index(drop=True, inplace=True)

In [20]:
dataframe.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,0,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [21]:
dataframe.loc[0,'ocorrencia_aerodromo'] = ''

In [22]:
dataframe.head(1)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [23]:
dataframe.loc[1] = 20

In [24]:
dataframe.head(2)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20

In [25]:
dataframe.loc[:,'total_recomendacoes'] = 10

In [26]:
dataframe

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,10,20,20
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04 00:00:00,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05 00:00:00,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,2020-12-29 00:00:00,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,2020-12-30 00:00:00,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,2020-12-30 00:00:00,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,2020-12-31 00:00:00,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,2020-12-31 00:00:00,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO

In [27]:
dataframe['ocorrencia_uf_bkp'] = dataframe.ocorrencia_uf

In [28]:
dataframe

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,INCIDENTE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,TO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MS
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ

In [29]:
dataframe.loc[dataframe.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

In [30]:
dataframe

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,GRAVE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,TO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,00:54:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MS
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,13:24:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ

In [31]:
dataframe.loc[dataframe.ocorrencia_uf == 'SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
11,40069,40069,40069,40069,GRAVE,-23.5069444444,-46.6341666667,SÃO PAULO,SP,BRASIL,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,2012-11-19,10,1,NÃO,SP
16,39809,39809,39809,39809,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,15:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
18,39828,39828,39828,39828,GRAVE,***,***,SANTOS,SP,BRASIL,...,17:45:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
26,39847,39847,39847,39847,GRAVE,NaN,NaN,SOROCABA,SP,BRASIL,...,13:10:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
27,39768,39768,39768,39768,GRAVE,NaN,NaN,CAMPINAS,SP,BRASIL,...,20:45:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5704,79739,79739,79739,79739,GRAVE,-23.62611111111,-46.65638888888,SÃO PAULO,SP,BRASIL,...,14:42:00,SIM,ATIVA,IG-144/CENIPA/2020,NÃO,NaN,10,2,NÃO,SP
5705,79705,79705,79705,79705,GRAVE,-23.483056,-47.486389,SOROCABA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5715,79718,79718,79718,79718,GRAVE,-23.509174,-46.637148,SÃO PAULO,SP,BRASIL,...,13:50:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
5742,79800,79800,79800,79800,GRAVE,-23.506667,-46.633889,SÃO PAULO,SP,BRASIL,...,10:15:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
5747,79804,79804,79804,79804,GRAVE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP

## Limpando os dados

In [32]:
dataframe.loc[dataframe.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [33]:
dataframe.replace(['**','###!','####','****','*****','NULL'], pd.NA, inplace=True)

In [34]:
dataframe.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1568
ocorrencia_longitude              1569
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2348
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     341
investigacao_status                340
divulgacao_relatorio_numero        871
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4257
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [35]:
dataframe.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1568
ocorrencia_longitude              1569
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2348
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     341
investigacao_status                340
divulgacao_relatorio_numero        871
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4257
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [36]:
dataframe.fillna(10, inplace=True)

In [37]:
dataframe.isnull().sum()

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
ocorrencia_uf_bkp                 0
dtype: int64

In [38]:
dataframe.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,10,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RS

In [39]:
dataframe.replace([10], pd.NA, inplace=True)

In [40]:
dataframe.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1568
ocorrencia_longitude              1569
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2348
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     341
investigacao_status                340
divulgacao_relatorio_numero        871
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4257
total_recomendacoes               5752
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [41]:
dataframe.fillna(value={'total_recomendacoes':10}, inplace=True)

In [42]:
dataframe.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1568
ocorrencia_longitude              1569
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo              2348
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     341
investigacao_status                340
divulgacao_relatorio_numero        871
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4257
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    0
dtype: int64

In [43]:
dataframe['total_recomendacoes_bkp'] = dataframe.total_recomendacoes

In [44]:
dataframe.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp,total_recomendacoes_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ,10
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,10,20,20,20,10
2,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RJ,10
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT,10
4,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,...,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RS,10

In [45]:
dataframe.drop(['total_recomendacoes_bkp'], axis=1, inplace=True)

In [46]:
dataframe.dropna()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
8,39156,39156,39156,39156,INCIDENTE GRAVE,-15.2402777778,-59.3541666667,CASCAVEL,PR,BRASIL,...,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,2011-06-30,10,1,NÃO,PR
11,40069,40069,40069,40069,GRAVE,-23.5069444444,-46.6341666667,SÃO PAULO,SP,BRASIL,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,2012-11-19,10,1,NÃO,SP
14,40107,40107,40107,40107,ACIDENTE,-1.4169444444,-51.6338888889,GURUPÁ,PA,BRASIL,...,14:30:00,SIM,FINALIZADA,A-505/CENIPA/2016,SIM,2016-03-18,10,1,NÃO,PA
29,39709,39709,39709,39709,INCIDENTE GRAVE,-25.4033333333,-49.2336111111,CURITIBA,PR,BRASIL,...,16:36:00,***,FINALIZADA,IG-029/CENIPA/2011,SIM,2011-07-21,10,1,SIM,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4873,78626,78626,78626,78626,ACIDENTE,-207.241.666.66,-458.638.888.88,GUAPÉ,MG,BRASIL,...,15:10:00,SIM,FINALIZADA,A-053/CENIPA/2019,SIM,2019-09-03,10,1,NÃO,MG
4935,78828,78828,78828,78828,INCIDENTE GRAVE,***,***,JEQUIÉ,BA,BRASIL,...,20:40:00,SIM,FINALIZADA,IG-078/CENIPA/2019,SIM,2019-10-28,10,1,NÃO,BA
4971,78749,78749,78749,78749,ACIDENTE,-2.896667,-40.856944,CAMOCIM,CE,BRASIL,...,14:30:00,SIM,FINALIZADA,A-096/CENIPA/2019,SIM,2019-10-28,10,1,SIM,CE
5008,78766,78766,78766,78766,ACIDENTE,-7.599444,-72.769444,CRUZEIRO DO SUL,AC,BRASIL,...,21:40:00,SIM,FINALIZADA,A-113/CENIPA/2019,SIM,2020-12-29,10,1,NÃO,AC
5280,79124,79124,79124,79124,GRAVE,-22.216667,-47.360833,LEME,SP,BRASIL,...,17:00:00,SIM,FINALIZADA,A-010/CENIPA/2020,SIM,2021-02-12,10,1,NÃO,SP

In [47]:

dataframe.dropna(subset=['ocorrencia_uf'])

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,GRAVE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,SP
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,TO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,00:54:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,MS
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,13:24:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ

In [48]:

dataframe.drop_duplicates(inplace=True)

In [49]:
dataframe

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,40351,40351,40351,40351,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RJ
3,39527,39527,39527,39527,ACIDENTE,-13.1066666667,-55.9930555556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,2019-10-28,10,1,NÃO,MT
4,40324,40324,40324,40324,INCIDENTE,<NA>,<NA>,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,<NA>,NÃO,<NA>,10,1,NÃO,RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,79804,79804,79804,79804,GRAVE,-23.0069444444,-47.1344444444,CAMPINAS,SP,BRASIL,...,19:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,SP
5748,79757,79757,79757,79757,INCIDENTE GRAVE,-10.804722,-49.756389,LAGOA DA CONFUSÃO,TO,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,TO
5749,79802,79802,79802,79802,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,...,00:54:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ
5750,79756,79756,79756,79756,INCIDENTE GRAVE,-22.507222,-54.364167,VICENTINA,MS,BRASIL,...,09:00:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,MS
5751,79844,79844,79844,79844,INCIDENTE,"-22,9875","-43,37",RIO DE JANEIRO,RJ,BRASIL,...,13:24:00,SIM,FINALIZADA,***,NÃO,<NA>,10,1,NÃO,RJ